//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssortmentExtra
    {
        public int ID { get; set; }
        public string Breed { get; set; }
        public string RankH { get; set; }
        public string ThicknessLevel { get; set; }
        public string H { get; set; }
        public string VInBark { get; set; }
        public string UnitOfMeasure { get; set; }
        public string Large { get; set; }
        public string Average1 { get; set; }
        public string Average2 { get; set; }
        public string Small { get; set; }
        public string Total { get; set; }
        public string PlywoodLog { get; set; }
        public string Sawlog { get; set; }
        public string CommodityRidge { get; set; }
        public string Stroyles { get; set; }
        public string Podtovarnik { get; set; }
        public string TechnologicalRawMaterials { get; set; }
        public string FirewoodFuel { get; set; }
        public string Waste { get; set; }
        public string TechnologicalRawMaterialsFirewood { get; set; }
        public string FirewoodFuelFirewood { get; set; }
        public string WasteFirewood { get; set; }
        public string Bark { get; set; }
    }
}
