//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssortmentLinden
    {
        public int ID { get; set; }
        public string Breed { get; set; }
        public string RankH { get; set; }
        public string ThicknessLevel { get; set; }
        public string H { get; set; }
        public string VInBark { get; set; }
        public string Large1 { get; set; }
        public string Large2 { get; set; }
        public string Large3 { get; set; }
        public string LargeTotal { get; set; }
        public string Average1_1 { get; set; }
        public string Average1_2 { get; set; }
        public string Average1_3 { get; set; }
        public string Average1Total { get; set; }
        public string Average2_1 { get; set; }
        public string Average2_2 { get; set; }
        public string Average2_3 { get; set; }
        public string Average2Total { get; set; }
        public string Small1 { get; set; }
        public string Small2 { get; set; }
        public string Small3 { get; set; }
        public string SmallTotal { get; set; }
        public string AllBusiness { get; set; }
        public string TechnologicalRawMaterials { get; set; }
        public string FirewoodFuel { get; set; }
        public string Waste { get; set; }
        public string Bark { get; set; }
        public string Total { get; set; }
    }
}
