//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ForestDamageAssessmentDbEntities : DbContext
    {
        public ForestDamageAssessmentDbEntities()
            : base("name=ForestDamageAssessmentDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Assortment> Assortment { get; set; }
        public virtual DbSet<AssortmentExtra> AssortmentExtra { get; set; }
        public virtual DbSet<AssortmentLinden> AssortmentLinden { get; set; }
        public virtual DbSet<BreedDiameterModel> BreedDiameterModel { get; set; }
        public virtual DbSet<RankHeights> RankHeights { get; set; }
        public virtual DbSet<Regions> Regions { get; set; }
        public virtual DbSet<STD> STD { get; set; }
        public virtual DbSet<TaxPrice> TaxPrice { get; set; }
    }
}
