//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class RankHeights
    {
        public int ID { get; set; }
        public string Breed { get; set; }
        public string ThicknessLevel { get; set; }
        public string MinH { get; set; }
        public string MaxH { get; set; }
        public Nullable<int> RankH { get; set; }
    }
}
